"""check_status

Revision ID: b7ba7c24ba0e
Revises: 202609030001
Create Date: 2026-09-04 10:55:49.066523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b7ba7c24ba0e'
down_revision = '202609030001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_log_actor_id_fkey'), 'activity_log', type_='foreignkey')
    op.create_foreign_key(None, 'activity_log', 'users', ['actor_id'], ['id'])
    op.drop_index(op.f('ix_candidates_search_current_company'), table_name='candidates', postgresql_ops={'lower(current_company::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_candidates_search_full_name'), table_name='candidates', postgresql_ops={'lower(full_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_candidates_search_skills'), table_name='candidates', postgresql_ops={'lower(skills::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_candidates_zoho_candidate_id'), 'candidates', type_='unique')
    op.alter_column('company_sectors', 'company_name',
               existing_type=sa.VARCHAR(length=500),
               comment='Company name (unique)',
               existing_nullable=False)
    op.alter_column('company_sectors', 'sector',
               existing_type=sa.VARCHAR(length=255),
               comment="Industry sector (e.g., 'Technology', 'Finance', 'Healthcare')",
               existing_nullable=False)
    op.alter_column('company_sectors', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment="Data source: 'manual', 'api', 'ml_prediction', 'crunchbase', etc.",
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('company_sectors', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score for ML predictions (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('company_sectors', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata: alternate names, tags, classifications, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('duplicate_reviews_candidate_id_fkey'), 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(op.f('duplicate_reviews_matched_candidate_id_fkey'), 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(op.f('duplicate_reviews_jd_id_fkey'), 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(op.f('duplicate_reviews_reviewed_by_fkey'), 'duplicate_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'duplicate_reviews', 'job_descriptions', ['jd_id'], ['id'])
    op.create_foreign_key(None, 'duplicate_reviews', 'users', ['reviewed_by'], ['id'])
    op.create_foreign_key(None, 'duplicate_reviews', 'candidates', ['matched_candidate_id'], ['id'])
    op.create_foreign_key(None, 'duplicate_reviews', 'candidates', ['candidate_id'], ['id'])
    op.alter_column('generated_resumes', 'format',
               existing_type=sa.VARCHAR(length=20),
               comment="Output format: 'docx' or 'pdf'",
               existing_nullable=False)
    op.alter_column('generated_resumes', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment="Filesystem path to generated file (e.g., 'output/user_uuid/resume_generated_uuid.docx')",
               existing_nullable=False)
    op.alter_column('generated_resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment='Size of generated file in bytes',
               existing_nullable=True)
    op.alter_column('generated_resumes', 'generation_status',
               existing_type=sa.VARCHAR(length=50),
               comment="Generation status: 'generating', 'generated', 'failed'",
               existing_nullable=False,
               existing_server_default=sa.text("'generated'::character varying"))
    op.alter_column('generated_resumes', 'generation_error',
               existing_type=sa.TEXT(),
               comment='Error message if generation failed',
               existing_nullable=True)
    op.alter_column('generated_resumes', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata: generation flags, rendering options, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_integration_settings_status'), table_name='integration_settings')
    op.drop_constraint(op.f('uq_integration_settings_provider'), 'integration_settings', type_='unique')
    op.drop_constraint(op.f('uq_job_descriptions_jd_code'), 'job_descriptions', type_='unique')
    op.drop_constraint(op.f('ranking_criteria_jd_id_fkey'), 'ranking_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'ranking_criteria', 'job_descriptions', ['jd_id'], ['id'])
    op.alter_column('resume_embeddings', 'section_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Section type: 'summary', 'experience', 'skills', 'education', 'project', etc.",
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'section_index',
               existing_type=sa.INTEGER(),
               comment='Index within section (e.g., 2nd experience entry = index 2)',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'section_text',
               existing_type=sa.TEXT(),
               comment='Full text of this section for embedding',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'embedding',
               existing_type=sa.TEXT(),
               comment='Serialized embedding; vector-search implementation remains pending approval',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata: confidence, processing flags, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resume_templates', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               comment="Unique template identifier (e.g., 'kanini-default', 'deloitte-2024')",
               existing_nullable=False)
    op.alter_column('resume_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               comment="Human-readable template name (e.g., 'Kanini Resume Template')",
               existing_nullable=False)
    op.alter_column('resume_templates', 'template_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Template type: 'builtin', 'user_custom', or 'system'",
               existing_nullable=False)
    op.alter_column('resume_templates', 'user_id',
               existing_type=sa.UUID(),
               comment='User ID for custom templates; NULL for built-in templates',
               existing_nullable=True)
    op.alter_column('resume_templates', 'template_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Template specification: layout, sections, styling, font configs, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resume_templates', 'template_file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment="Filesystem path to template DOCX file (e.g., 'templates/kanini-template.docx')",
               existing_nullable=False)
    op.alter_column('resume_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether template is available for use',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('resume_templates', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment="Template version identifier (e.g., '2.0.1')",
               existing_nullable=True)
    op.alter_column('resume_templates', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata: creation details, tags, description, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique session identifier for this resume processing session',
               existing_nullable=False)
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=500),
               comment="Original uploaded filename (e.g., 'john_doe_resume.pdf')",
               existing_nullable=False)
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment="Filesystem path to uploaded file (e.g., 'uploads/user_uuid/filename.pdf')",
               existing_nullable=False)
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment='Size of uploaded file in bytes',
               existing_nullable=True)
    op.alter_column('resumes', 'file_format',
               existing_type=sa.VARCHAR(length=10),
               comment="File format: 'pdf', 'docx', or 'txt'",
               existing_nullable=False)
    op.alter_column('resumes', 'parsed_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Parsed resume content as structured JSON (name, email, skills, experience, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'normalization_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Normalized data (standardized degree names, skill mappings, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment="Workflow status: 'uploaded', 'parsing', 'parsed', 'reviewing', 'completed', 'failed'",
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::character varying"))
    op.alter_column('resumes', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata: parse errors, warnings, processing flags, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('saved_filters_recruiter_id_fkey'), 'saved_filters', type_='foreignkey')
    op.drop_constraint(op.f('saved_filters_jd_id_fkey'), 'saved_filters', type_='foreignkey')
    op.create_foreign_key(None, 'saved_filters', 'job_descriptions', ['jd_id'], ['id'])
    op.create_foreign_key(None, 'saved_filters', 'users', ['recruiter_id'], ['id'])
    op.drop_index(op.f('ix_shortlist_candidates_candidate_id'), table_name='shortlist_candidates')
    op.drop_constraint(op.f('shortlist_candidates_shortlist_id_fkey'), 'shortlist_candidates', type_='foreignkey')
    op.drop_constraint(op.f('shortlist_candidates_candidate_id_fkey'), 'shortlist_candidates', type_='foreignkey')
    op.create_foreign_key(None, 'shortlist_candidates', 'shortlists', ['shortlist_id'], ['id'])
    op.create_foreign_key(None, 'shortlist_candidates', 'candidates', ['candidate_id'], ['id'])
    op.drop_constraint(op.f('shortlists_recruiter_id_fkey'), 'shortlists', type_='foreignkey')
    op.drop_constraint(op.f('shortlists_jd_id_fkey'), 'shortlists', type_='foreignkey')
    op.create_foreign_key(None, 'shortlists', 'users', ['recruiter_id'], ['id'])
    op.create_foreign_key(None, 'shortlists', 'job_descriptions', ['jd_id'], ['id'])
    op.drop_constraint(op.f('sync_logs_triggered_by_fkey'), 'sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'sync_logs', 'users', ['triggered_by'], ['id'])
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'sync_logs', type_='foreignkey')
    op.create_foreign_key(op.f('sync_logs_triggered_by_fkey'), 'sync_logs', 'users', ['triggered_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'shortlists', type_='foreignkey')
    op.drop_constraint(None, 'shortlists', type_='foreignkey')
    op.create_foreign_key(op.f('shortlists_jd_id_fkey'), 'shortlists', 'job_descriptions', ['jd_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('shortlists_recruiter_id_fkey'), 'shortlists', 'users', ['recruiter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shortlist_candidates', type_='foreignkey')
    op.drop_constraint(None, 'shortlist_candidates', type_='foreignkey')
    op.create_foreign_key(op.f('shortlist_candidates_candidate_id_fkey'), 'shortlist_candidates', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('shortlist_candidates_shortlist_id_fkey'), 'shortlist_candidates', 'shortlists', ['shortlist_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_shortlist_candidates_candidate_id'), 'shortlist_candidates', ['candidate_id'], unique=False)
    op.drop_constraint(None, 'saved_filters', type_='foreignkey')
    op.drop_constraint(None, 'saved_filters', type_='foreignkey')
    op.create_foreign_key(op.f('saved_filters_jd_id_fkey'), 'saved_filters', 'job_descriptions', ['jd_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('saved_filters_recruiter_id_fkey'), 'saved_filters', 'users', ['recruiter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('resumes', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata: parse errors, warnings, processing flags, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Workflow status: 'uploaded', 'parsing', 'parsed', 'reviewing', 'completed', 'failed'",
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::character varying"))
    op.alter_column('resumes', 'normalization_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Normalized data (standardized degree names, skill mappings, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'parsed_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Parsed resume content as structured JSON (name, email, skills, experience, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'file_format',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="File format: 'pdf', 'docx', or 'txt'",
               existing_nullable=False)
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Size of uploaded file in bytes',
               existing_nullable=True)
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment="Filesystem path to uploaded file (e.g., 'uploads/user_uuid/filename.pdf')",
               existing_nullable=False)
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="Original uploaded filename (e.g., 'john_doe_resume.pdf')",
               existing_nullable=False)
    op.alter_column('resumes', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique session identifier for this resume processing session',
               existing_nullable=False)
    op.alter_column('resume_templates', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata: creation details, tags, description, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resume_templates', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Template version identifier (e.g., '2.0.1')",
               existing_nullable=True)
    op.alter_column('resume_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether template is available for use',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('resume_templates', 'template_file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment="Filesystem path to template DOCX file (e.g., 'templates/kanini-template.docx')",
               existing_nullable=False)
    op.alter_column('resume_templates', 'template_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Template specification: layout, sections, styling, font configs, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resume_templates', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID for custom templates; NULL for built-in templates',
               existing_nullable=True)
    op.alter_column('resume_templates', 'template_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Template type: 'builtin', 'user_custom', or 'system'",
               existing_nullable=False)
    op.alter_column('resume_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Human-readable template name (e.g., 'Kanini Resume Template')",
               existing_nullable=False)
    op.alter_column('resume_templates', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Unique template identifier (e.g., 'kanini-default', 'deloitte-2024')",
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata: confidence, processing flags, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resume_embeddings', 'embedding',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Serialized embedding; vector-search implementation remains pending approval',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'section_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full text of this section for embedding',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'section_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Index within section (e.g., 2nd experience entry = index 2)',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'section_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Section type: 'summary', 'experience', 'skills', 'education', 'project', etc.",
               existing_nullable=False)
    op.drop_constraint(None, 'ranking_criteria', type_='foreignkey')
    op.create_foreign_key(op.f('ranking_criteria_jd_id_fkey'), 'ranking_criteria', 'job_descriptions', ['jd_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_job_descriptions_jd_code'), 'job_descriptions', ['jd_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_integration_settings_provider'), 'integration_settings', ['provider'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_integration_settings_status'), 'integration_settings', ['status'], unique=False)
    op.alter_column('generated_resumes', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata: generation flags, rendering options, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('generated_resumes', 'generation_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if generation failed',
               existing_nullable=True)
    op.alter_column('generated_resumes', 'generation_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Generation status: 'generating', 'generated', 'failed'",
               existing_nullable=False,
               existing_server_default=sa.text("'generated'::character varying"))
    op.alter_column('generated_resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Size of generated file in bytes',
               existing_nullable=True)
    op.alter_column('generated_resumes', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment="Filesystem path to generated file (e.g., 'output/user_uuid/resume_generated_uuid.docx')",
               existing_nullable=False)
    op.alter_column('generated_resumes', 'format',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Output format: 'docx' or 'pdf'",
               existing_nullable=False)
    op.drop_constraint(None, 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(None, 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(None, 'duplicate_reviews', type_='foreignkey')
    op.drop_constraint(None, 'duplicate_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('duplicate_reviews_reviewed_by_fkey'), 'duplicate_reviews', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('duplicate_reviews_jd_id_fkey'), 'duplicate_reviews', 'job_descriptions', ['jd_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('duplicate_reviews_matched_candidate_id_fkey'), 'duplicate_reviews', 'candidates', ['matched_candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('duplicate_reviews_candidate_id_fkey'), 'duplicate_reviews', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.alter_column('company_sectors', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata: alternate names, tags, classifications, etc.',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('company_sectors', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence score for ML predictions (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('company_sectors', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Data source: 'manual', 'api', 'ml_prediction', 'crunchbase', etc.",
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('company_sectors', 'sector',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Industry sector (e.g., 'Technology', 'Finance', 'Healthcare')",
               existing_nullable=False)
    op.alter_column('company_sectors', 'company_name',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Company name (unique)',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_candidates_zoho_candidate_id'), 'candidates', ['zoho_candidate_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_candidates_search_skills'), 'candidates', [sa.literal_column('lower(skills::text)')], unique=False, postgresql_ops={'lower(skills::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_candidates_search_full_name'), 'candidates', [sa.literal_column('lower(full_name::text)')], unique=False, postgresql_ops={'lower(full_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_candidates_search_current_company'), 'candidates', [sa.literal_column('lower(current_company::text)')], unique=False, postgresql_ops={'lower(current_company::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.create_foreign_key(op.f('activity_log_actor_id_fkey'), 'activity_log', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
